import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import multer from 'multer';
import XLSX from 'xlsx';
import { existsSync, mkdirSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { initDb, db, all, one, notify } from './db.js';
import { auth, allow, coordinator, operational, signToken, supportOnly, supportOrHod } from './auth.js';

initDb();
mkdirSync('uploads/reminders',{recursive:true});
const app=express(); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const reminderUpload=multer({storage:multer.diskStorage({destination:'uploads/reminders',filename:(req,file,done)=>done(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${path.extname(file.originalname).toLowerCase()}`)}),limits:{fileSize:25*1024*1024},fileFilter:(req,file,done)=>done(null,/^(image|audio|video)\//.test(file.mimetype))});
app.use(cors()); app.use(express.json()); app.use('/uploads',express.static(path.resolve('uploads')));
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const publicUser=u=>{
  const assignments=all(`SELECT a.assignment_role,g.name game FROM assignments a LEFT JOIN games g ON g.id=a.game_id WHERE a.teacher_id=? AND a.status='ACTIVE' ORDER BY CASE WHEN a.assignment_role='SUPPORT_COORDINATOR' THEN 0 ELSE 1 END,a.assigned_at DESC`,u.id);
  const primary=assignments[0];
  const displayRole=u.base_role==='SUPER_ADMIN'?'Super Administrator':u.base_role==='HOD'?'Head of Department':primary?.assignment_role==='SUPPORT_COORDINATOR'?'Support Coordinator':primary?.game?`${primary.game} Game Head`:'Faculty Member';
  return {id:u.id,name:u.name,email:u.email,baseRole:u.base_role,displayRole,department:u.department,phone:u.phone,status:u.status};
};
const sheetScope=user=>{
  const visible=(condition,params)=>({where:`WHERE (${condition}) AND NOT EXISTS (SELECT 1 FROM sheet_deletions sd WHERE sd.sheet_id=s.id AND sd.user_id=?)`,params:[...params,user.id]});
  if(user.base_role==='SUPER_ADMIN') return {where:'WHERE 1=0',params:[]};
  if(user.base_role==='HOD') return visible("s.submitted_by=? OR s.id IN (SELECT sheet_id FROM forwards WHERE forwarded_to=? OR audience='HOD')",[user.id,user.id]);
  const support=one("SELECT id FROM assignments WHERE teacher_id=? AND assignment_role='SUPPORT_COORDINATOR' AND status='ACTIVE'",user.id);
  if(support) return visible("s.submitted_by=? OR s.status='SUBMITTED' OR s.id IN (SELECT sheet_id FROM forwards WHERE forwarded_to=?)",[user.id,user.id]);
  return visible("s.submitted_by=? OR s.id IN (SELECT sheet_id FROM forwards WHERE forwarded_to=? OR audience IN ('ALL_TEACHERS','ALL_COORDINATORS'))",[user.id,user.id]);
};
const canAccessTerm=(user,termId)=>{
  const support=one("SELECT id FROM assignments WHERE teacher_id=? AND assignment_role='SUPPORT_COORDINATOR' AND status='ACTIVE'",user.id);
  return !!support||!!one('SELECT id FROM term_forwards WHERE term_id=? AND forwarded_to=?',termId,user.id);
};

app.post('/api/auth/login',wrap(async(req,res)=>{
  const user=one('SELECT * FROM users WHERE lower(email)=lower(?)',req.body.email||'');
  if(!user || user.status!=='ACTIVE' || !await bcrypt.compare(req.body.password||'',user.password_hash)) return res.status(401).json({message:'Invalid email or password'});
  res.json({token:signToken(user),user:publicUser(user)});
}));
app.get('/api/auth/me',auth,(req,res)=>res.json(publicUser(req.user)));

app.get('/api/dashboard',auth,(req,res)=>{
  const uid=req.user.id;
  const assignments=all(`SELECT a.id,a.assignment_role role,a.assigned_at,g.id gameId,g.name game,u.name assignedBy FROM assignments a LEFT JOIN games g ON g.id=a.game_id JOIN users u ON u.id=a.assigned_by WHERE a.teacher_id=? AND a.status='ACTIVE'`,uid);
  const scope=sheetScope(req.user);
  const scopeCondition=scope.where.replace(/^WHERE\s+/,'');
  const visibleSubmitted=one(`SELECT COUNT(*) n FROM sheets s WHERE s.status='SUBMITTED' AND (${scopeCondition})`,...scope.params).n;
  const visiblePending=one(`SELECT COUNT(*) n FROM sheets s WHERE s.status='DRAFT' AND (${scopeCondition})`,...scope.params).n;
  const stats={teachers:one("SELECT COUNT(*) n FROM users WHERE base_role='TEACHER'").n,hods:one("SELECT COUNT(*) n FROM users WHERE base_role='HOD'").n,activeUsers:one("SELECT COUNT(*) n FROM users WHERE status='ACTIVE'").n,inactiveUsers:one("SELECT COUNT(*) n FROM users WHERE status='INACTIVE'").n,games:one('SELECT COUNT(*) n FROM games').n,activeGames:one("SELECT COUNT(*) n FROM games WHERE status='ACTIVE'").n,coordinators:one("SELECT COUNT(DISTINCT teacher_id) n FROM assignments WHERE status='ACTIVE'").n,sheets:visibleSubmitted,pending:visiblePending};
  const recentSheets=all(`SELECT s.id,s.title,s.status,s.created_at createdAt,s.submitted_at submittedAt,g.name game,u.name submittedBy,u.id submittedById,CASE WHEN s.submitted_by=? OR EXISTS (SELECT 1 FROM forwards fd WHERE fd.sheet_id=s.id AND fd.forwarded_by=?) THEN 'SENT' ELSE 'RECEIVED' END direction,(SELECT COUNT(*) FROM student_records r WHERE r.sheet_id=s.id) playerCount FROM sheets s JOIN games g ON g.id=s.game_id JOIN users u ON u.id=s.submitted_by ${scope.where} ORDER BY s.created_at DESC LIMIT 12`,req.user.id,req.user.id,...scope.params);
  const notifications=all("SELECT n.*,u.name sender_name,'RECEIVED' direction FROM notifications n LEFT JOIN users u ON u.id=n.sender_id WHERE n.user_id=? AND n.type!='REMINDER' ORDER BY n.created_at DESC LIMIT 6",uid);
  res.json({stats,assignments,recentSheets,notifications});
});

app.get('/api/users',auth,(req,res)=>res.json(all(`SELECT u.id,u.name,u.email,u.base_role baseRole,u.department,u.phone,u.status,u.created_at createdAt,GROUP_CONCAT(CASE WHEN a.status='ACTIVE' THEN COALESCE(g.name||' Game Head',CASE WHEN a.assignment_role='SUPPORT_COORDINATOR' THEN 'Support Coordinator' ELSE a.assignment_role END) END) assignments,(SELECT sa.id FROM assignments sa WHERE sa.teacher_id=u.id AND sa.assignment_role='SUPPORT_COORDINATOR' AND sa.status='ACTIVE' LIMIT 1) supportAssignmentId FROM users u LEFT JOIN assignments a ON a.teacher_id=u.id LEFT JOIN games g ON g.id=a.game_id GROUP BY u.id ORDER BY u.created_at DESC`)));
app.post('/api/users',auth,allow('SUPER_ADMIN'),wrap(async(req,res)=>{
  const {name,email,password,baseRole='TEACHER',department,phone}=req.body;
  if(!name||!email||!password) return res.status(400).json({message:'Name, email and password are required'});
  const result=db.prepare('INSERT INTO users (name,email,password_hash,base_role,department,phone) VALUES (?,?,?,?,?,?)').run(name,email,await bcrypt.hash(password,10),baseRole,department||'Faculty of Computing',phone||'');
  res.status(201).json({id:Number(result.lastInsertRowid),message:'Account created successfully'});
}));
app.patch('/api/users/:id',auth,allow('SUPER_ADMIN'),wrap(async(req,res)=>{
  const u=one('SELECT * FROM users WHERE id=?',req.params.id); if(!u)return res.status(404).json({message:'User not found'});
  db.prepare('UPDATE users SET name=?,email=?,base_role=?,department=?,phone=?,status=? WHERE id=?').run(req.body.name??u.name,req.body.email??u.email,req.body.baseRole??u.base_role,req.body.department??u.department,req.body.phone??u.phone,req.body.status??u.status,u.id);
  if(req.body.password) db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(await bcrypt.hash(req.body.password,10),u.id);
  res.json({message:'User updated'});
}));

app.get('/api/games',auth,operational,(req,res)=>res.json(all(`SELECT g.id,g.name,g.description,g.status,g.created_at createdAt,GROUP_CONCAT(CASE WHEN a.status='ACTIVE' THEN u.name END) coordinators,COUNT(CASE WHEN a.status='ACTIVE' THEN 1 END) coordinatorCount FROM games g LEFT JOIN assignments a ON a.game_id=g.id LEFT JOIN users u ON u.id=a.teacher_id GROUP BY g.id ORDER BY g.name`)));
app.post('/api/games',auth,coordinator,(req,res)=>{const r=db.prepare('INSERT INTO games(name,description,created_by) VALUES(?,?,?)').run(req.body.name,req.body.description||'',req.user.id); res.status(201).json({id:Number(r.lastInsertRowid),message:'Game created'});});
app.patch('/api/games/:id',auth,coordinator,(req,res)=>{const g=one('SELECT * FROM games WHERE id=?',req.params.id);if(!g)return res.status(404).json({message:'Game not found'});db.prepare('UPDATE games SET name=?,description=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.body.name??g.name,req.body.description??g.description,req.body.status??g.status,g.id);res.json({message:'Game updated'});});
app.delete('/api/games/:id',auth,supportOrHod,(req,res)=>{const game=one('SELECT * FROM games WHERE id=?',req.params.id);if(!game)return res.status(404).json({message:'Game not found'});db.exec('BEGIN');try{db.prepare('DELETE FROM forwards WHERE sheet_id IN (SELECT id FROM sheets WHERE game_id=?)').run(game.id);db.prepare('DELETE FROM sheet_deletions WHERE sheet_id IN (SELECT id FROM sheets WHERE game_id=?)').run(game.id);db.prepare('DELETE FROM student_records WHERE game_id=?').run(game.id);db.prepare('DELETE FROM sheets WHERE game_id=?').run(game.id);db.prepare('DELETE FROM assignments WHERE game_id=?').run(game.id);db.prepare('DELETE FROM games WHERE id=?').run(game.id);db.exec('COMMIT');res.json({message:`${game.name} permanently deleted`});}catch(error){db.exec('ROLLBACK');throw error;}});

app.post('/api/assignments/support',auth,allow('HOD'),(req,res)=>{
  const current=one("SELECT a.id,u.name FROM assignments a JOIN users u ON u.id=a.teacher_id WHERE a.assignment_role='SUPPORT_COORDINATOR' AND a.status='ACTIVE'");
  if(current)return res.status(409).json({message:`${current.name} is already the Support Coordinator. Remove the current assignment first.`});
  db.prepare("INSERT INTO assignments(teacher_id,assignment_role,assigned_by) VALUES(?,'SUPPORT_COORDINATOR',?)").run(req.body.teacherId,req.user.id);
  notify(req.body.teacherId,'Support Coordinator assignment',`You were appointed Support Coordinator by ${req.user.name}.`,'ASSIGNMENT',req.user.id,'/'); res.json({message:'Support Coordinator assigned'});
});
app.post('/api/assignments/game',auth,supportOrHod,(req,res)=>{
  db.prepare("INSERT INTO assignments(teacher_id,assignment_role,game_id,assigned_by) VALUES(?,'GAME_COORDINATOR',?,?)").run(req.body.teacherId,req.body.gameId,req.user.id);
  const game=one('SELECT name FROM games WHERE id=?',req.body.gameId); notify(req.body.teacherId,`${game.name} Game Head`,`You were assigned as ${game.name} Game Head by ${req.user.name}.`,'ASSIGNMENT',req.user.id,'/games');
  all("SELECT id FROM users WHERE base_role='HOD'").forEach(h=>notify(h.id,'Game Head assigned',`${req.user.name} assigned a Game Head for ${game.name}.`,'ASSIGNMENT',req.user.id,'/games'));res.json({message:'Game Head assigned'});
});
app.delete('/api/assignments/:id',auth,supportOrHod,(req,res)=>{const assignment=one('SELECT * FROM assignments WHERE id=? AND status=\'ACTIVE\'',req.params.id);if(!assignment)return res.status(404).json({message:'Active assignment not found'});if(assignment.assignment_role==='SUPPORT_COORDINATOR'&&req.user.base_role!=='HOD')return res.status(403).json({message:'Only HOD can remove the Support Coordinator'});db.prepare("UPDATE assignments SET status='INACTIVE' WHERE id=?").run(assignment.id);res.json({message:'Assignment removed'});});

app.get('/api/sheets',auth,operational,(req,res)=>{const scope=sheetScope(req.user);res.json(all(`SELECT s.id,s.title,s.status,s.notes,s.file_name fileName,s.created_at createdAt,s.submitted_at submittedAt,g.id gameId,g.name game,u.name submittedBy,u.id submittedById,CASE WHEN s.submitted_by=? OR EXISTS (SELECT 1 FROM forwards fd WHERE fd.sheet_id=s.id AND fd.forwarded_by=?) THEN 'SENT' ELSE 'RECEIVED' END direction,COUNT(r.id) playerCount FROM sheets s JOIN games g ON g.id=s.game_id JOIN users u ON u.id=s.submitted_by LEFT JOIN student_records r ON r.sheet_id=s.id ${scope.where} GROUP BY s.id ORDER BY s.created_at DESC`,req.user.id,req.user.id,...scope.params));});
app.post('/api/sheets',auth,coordinator,(req,res)=>{const r=db.prepare('INSERT INTO sheets(title,game_id,submitted_by,notes) VALUES(?,?,?,?)').run(req.body.title,req.body.gameId,req.user.id,req.body.notes||'');res.status(201).json({id:Number(r.lastInsertRowid),message:'Draft sheet created'});});
app.get('/api/sheets/:id/export',auth,operational,(req,res)=>{const scope=sheetScope(req.user);const condition=scope.where.replace(/^WHERE\s+/,'');const sheet=one(`SELECT s.id,s.title,g.name game,u.name submittedBy FROM sheets s JOIN games g ON g.id=s.game_id JOIN users u ON u.id=s.submitted_by WHERE s.id=? AND (${condition})`,req.params.id,...scope.params);if(!sheet)return res.status(403).json({message:'This sheet is not available to you'});const records=all(`SELECT student_name 'Student Name',registration_no 'Registration Number',department 'Department',semester 'Semester',section 'Section',contact_no 'Contact Number',? 'Game Name',remarks 'Remarks' FROM student_records WHERE sheet_id=? ORDER BY id`,sheet.game,sheet.id);const workbook=XLSX.utils.book_new();const worksheet=XLSX.utils.json_to_sheet(records);worksheet['!cols']=[{wch:24},{wch:24},{wch:25},{wch:12},{wch:10},{wch:18},{wch:20},{wch:24}];XLSX.utils.book_append_sheet(workbook,worksheet,'Player Records');const info=XLSX.utils.aoa_to_sheet([['Sheet',sheet.title],['Game',sheet.game],['Prepared By',sheet.submittedBy],['Exported At',new Date().toISOString()]]);XLSX.utils.book_append_sheet(workbook,info,'Sheet Information');const buffer=XLSX.write(workbook,{type:'buffer',bookType:'xlsx'});const filename=`${sheet.title.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')||'player-sheet'}.xlsx`;res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${filename}"`);res.send(buffer);});
app.get('/api/sheets/:id/records',auth,operational,(req,res)=>{const scope=sheetScope(req.user);const condition=scope.where.replace(/^WHERE\s+/,'');const visible=one(`SELECT s.id FROM sheets s WHERE s.id=? AND (${condition})`,req.params.id,...scope.params);if(!visible)return res.status(403).json({message:'This sheet has not been forwarded to you'});res.json(all('SELECT * FROM student_records WHERE sheet_id=? ORDER BY id DESC',req.params.id));});
app.delete('/api/sheets/:id',auth,operational,(req,res)=>{const scope=sheetScope(req.user);const condition=scope.where.replace(/^WHERE\s+/,'');const sheet=one(`SELECT s.* FROM sheets s WHERE s.id=? AND (${condition})`,req.params.id,...scope.params);if(!sheet)return res.status(404).json({message:'Sheet not found'});if(req.query.scope!=='everyone'){db.prepare('INSERT OR IGNORE INTO sheet_deletions(sheet_id,user_id) VALUES(?,?)').run(sheet.id,req.user.id);return res.json({message:'Sheet deleted for you'});}const support=one("SELECT id FROM assignments WHERE teacher_id=? AND assignment_role='SUPPORT_COORDINATOR' AND status='ACTIVE'",req.user.id);if(sheet.submitted_by!==req.user.id&&req.user.base_role!=='HOD'&&!support)return res.status(403).json({message:'Only the owner, HOD, or Support Coordinator can delete for everyone'});db.prepare('DELETE FROM forwards WHERE sheet_id=?').run(sheet.id);db.prepare('DELETE FROM sheet_deletions WHERE sheet_id=?').run(sheet.id);db.prepare('DELETE FROM sheets WHERE id=?').run(sheet.id);res.json({message:'Sheet deleted for everyone'});});
app.post('/api/sheets/:id/records',auth,coordinator,(req,res)=>{const s=one('SELECT * FROM sheets WHERE id=?',req.params.id);if(!s)return res.status(404).json({message:'Sheet not found'});const x=req.body;const r=db.prepare('INSERT INTO student_records(student_name,registration_no,department,semester,section,contact_no,game_id,remarks,added_by,sheet_id) VALUES(?,?,?,?,?,?,?,?,?,?)').run(x.studentName,x.registrationNo,x.department,x.semester||'',x.section||'',x.contactNo||'',s.game_id,x.remarks||'',req.user.id,s.id);res.status(201).json({id:Number(r.lastInsertRowid),message:'Player added'});});
app.patch('/api/records/:id',auth,coordinator,(req,res)=>{const x=req.body;db.prepare('UPDATE student_records SET student_name=?,registration_no=?,department=?,semester=?,section=?,contact_no=?,remarks=? WHERE id=?').run(x.studentName,x.registrationNo,x.department,x.semester||'',x.section||'',x.contactNo||'',x.remarks||'',req.params.id);res.json({message:'Player updated'});});
app.delete('/api/records/:id',auth,coordinator,(req,res)=>{db.prepare('DELETE FROM student_records WHERE id=?').run(req.params.id);res.json({message:'Player removed'});});
app.post('/api/sheets/:id/import',auth,coordinator,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({message:'Select an Excel file'});const s=one('SELECT * FROM sheets WHERE id=?',req.params.id);const rows=XLSX.utils.sheet_to_json(XLSX.read(req.file.buffer).Sheets[XLSX.read(req.file.buffer).SheetNames[0]],{defval:''});const ins=db.prepare('INSERT INTO student_records(student_name,registration_no,department,semester,section,contact_no,game_id,remarks,added_by,sheet_id) VALUES(?,?,?,?,?,?,?,?,?,?)');let count=0;for(const x of rows){const v=k=>x[k]??x[k.toLowerCase()]??'';if(!v('Student Name')||!v('Registration Number'))continue;ins.run(v('Student Name'),v('Registration Number'),v('Department'),String(v('Semester')),String(v('Section')),String(v('Contact Number')),s.game_id,v('Remarks'),req.user.id,s.id);count++;}db.prepare('UPDATE sheets SET file_name=? WHERE id=?').run(req.file.originalname,s.id);res.json({message:`${count} player records imported`,count});});
app.post('/api/sheets/:id/submit',auth,coordinator,(req,res)=>{db.prepare("UPDATE sheets SET status='SUBMITTED',submitted_at=CURRENT_TIMESTAMP WHERE id=?").run(req.params.id);const s=one('SELECT s.title,g.name game FROM sheets s JOIN games g ON g.id=s.game_id WHERE s.id=?',req.params.id);all("SELECT teacher_id id FROM assignments WHERE assignment_role='SUPPORT_COORDINATOR' AND status='ACTIVE'").forEach(u=>notify(u.id,'Player sheet submitted',`${req.user.name} submitted ${s.title} for ${s.game}. Review and forward it when ready.`,'SUBMISSION',req.user.id,`/sheets/${req.params.id}`));res.json({message:'Sheet submitted to Support Coordinator'});});
app.post('/api/sheets/:id/forward',auth,supportOrHod,(req,res)=>{const {userId,audience='USER',message=''}=req.body;db.prepare('INSERT INTO forwards(sheet_id,forwarded_by,forwarded_to,audience,message) VALUES(?,?,?,?,?)').run(req.params.id,req.user.id,userId||null,audience,message);const targets=userId?[{id:userId}]:all(audience==='ALL_TEACHERS'?"SELECT id FROM users WHERE base_role='TEACHER'":audience==='HOD'?"SELECT id FROM users WHERE base_role='HOD'":"SELECT DISTINCT teacher_id id FROM assignments WHERE status='ACTIVE'");targets.forEach(u=>notify(u.id,'Sheet forwarded',`${req.user.name} forwarded a player sheet to you.`,'FORWARD',req.user.id,`/sheets/${req.params.id}`));res.json({message:'Sheet forwarded'});});

app.get('/api/terms',auth,operational,(req,res)=>{const support=one("SELECT id FROM assignments WHERE teacher_id=? AND assignment_role='SUPPORT_COORDINATOR' AND status='ACTIVE'",req.user.id);const where=support?'':'WHERE EXISTS (SELECT 1 FROM term_forwards tf WHERE tf.term_id=t.id AND tf.forwarded_to=?)';const params=support?[]:[req.user.id];res.json(all(`SELECT t.id,t.code,t.name,t.status,t.created_at createdAt,(SELECT COUNT(*) FROM term_teacher_records tr WHERE tr.term_id=t.id) teacherCount,(SELECT COUNT(*) FROM term_student_records sr WHERE sr.term_id=t.id) studentCount FROM terms t ${where} ORDER BY CAST(t.code AS INTEGER) DESC`,...params));});
app.post('/api/terms',auth,supportOnly,(req,res)=>{const code=String(req.body.code||'').trim();const name=String(req.body.name||`Batch ${code}`).trim();if(!/^[A-Za-z0-9-]{2,10}$/.test(code))return res.status(400).json({message:'Use a 2–10 character batch code'});const result=db.prepare("INSERT INTO terms(code,name,status,created_by) VALUES(?,?,'ARCHIVED',?)").run(code,name,req.user.id);const termId=Number(result.lastInsertRowid);const teachers=all(`SELECT u.name,u.email,u.department,u.base_role baseRole,GROUP_CONCAT(CASE WHEN a.assignment_role='SUPPORT_COORDINATOR' THEN 'Support Coordinator' WHEN a.game_id IS NOT NULL THEN 'Game Head' END) assignedRole,GROUP_CONCAT(g.name) gameName FROM users u LEFT JOIN assignments a ON a.teacher_id=u.id AND a.status='ACTIVE' LEFT JOIN games g ON g.id=a.game_id WHERE u.base_role!='SUPER_ADMIN' GROUP BY u.id`);const insert=db.prepare('INSERT INTO term_teacher_records(term_id,teacher_name,email,department,base_role,assigned_role,game_name,remarks) VALUES(?,?,?,?,?,?,?,?)');teachers.forEach(teacher=>insert.run(termId,teacher.name,teacher.email,teacher.department,teacher.baseRole,teacher.assignedRole||'Teacher',teacher.gameName||null,'Snapshot captured at term creation'));res.status(201).json({id:termId,message:`Term ${code} created with current teacher snapshot`});});
app.get('/api/terms/recipients',auth,supportOnly,(req,res)=>res.json(all("SELECT id,name,email,base_role baseRole FROM users WHERE status='ACTIVE' AND base_role!='SUPER_ADMIN' AND id!=? ORDER BY CASE base_role WHEN 'HOD' THEN 0 ELSE 1 END,name",req.user.id)));
app.get('/api/terms/:id',auth,operational,(req,res)=>{if(!canAccessTerm(req.user,req.params.id))return res.status(403).json({message:'This term archive has not been shared with you'});const term=one('SELECT id,code,name,status,created_at createdAt FROM terms WHERE id=?',req.params.id);if(!term)return res.status(404).json({message:'Term not found'});res.json({term,games:all('SELECT name,status FROM games ORDER BY name'),teachers:all('SELECT id,teacher_name teacherName,email,department,base_role baseRole,assigned_role assignedRole,game_name gameName,remarks FROM term_teacher_records WHERE term_id=? ORDER BY teacher_name',term.id),students:all('SELECT id,student_name studentName,registration_no registrationNo,department,semester,section,contact_no contactNo,game_name gameName,remarks FROM term_student_records WHERE term_id=? ORDER BY student_name',term.id)});});
app.post('/api/terms/:id/import',auth,supportOnly,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({message:'Select an Excel file'});const term=one('SELECT id FROM terms WHERE id=?',req.params.id);if(!term)return res.status(404).json({message:'Term not found'});const workbook=XLSX.read(req.file.buffer);const rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});const insert=db.prepare('INSERT INTO term_student_records(term_id,student_name,registration_no,department,semester,section,contact_no,game_name,remarks) VALUES(?,?,?,?,?,?,?,?,?)');let count=0;for(const row of rows){const value=key=>row[key]??row[key.toLowerCase()]??'';if(!value('Student Name')||!value('Registration Number'))continue;insert.run(term.id,value('Student Name'),value('Registration Number'),value('Department'),String(value('Semester')),String(value('Section')),String(value('Contact Number')),value('Game Name'),value('Remarks'));count++;}res.json({message:`${count} historical student records imported`,count});});
app.get('/api/terms/:id/export',auth,operational,(req,res)=>{if(!canAccessTerm(req.user,req.params.id))return res.status(403).json({message:'This term archive has not been shared with you'});const term=one('SELECT * FROM terms WHERE id=?',req.params.id);if(!term)return res.status(404).json({message:'Term not found'});const type=['teachers','students'].includes(req.query.type)?req.query.type:'complete';const game=String(req.query.game||'');if(type==='students'&&!game)return res.status(400).json({message:'Select a game before downloading student records'});const teachers=all(`SELECT teacher_name 'Teacher Name',email 'Email',department 'Department',base_role 'Base Role',assigned_role 'Assigned Role',game_name 'Game / Head Responsibility',remarks 'Remarks' FROM term_teacher_records WHERE term_id=?`,term.id);const studentSql=`SELECT student_name 'Student Name',registration_no 'Registration Number',department 'Department',semester 'Semester',section 'Section',contact_no 'Contact Number',game_name 'Game Name',remarks 'Remarks' FROM term_student_records WHERE term_id=?${type==='students'?' AND game_name=?':''}`;const students=all(studentSql,...(type==='students'?[term.id,game]:[term.id]));const workbook=XLSX.utils.book_new();if(type!=='students'){const teacherSheet=XLSX.utils.json_to_sheet(teachers);teacherSheet['!cols']=[{wch:24},{wch:28},{wch:24},{wch:16},{wch:22},{wch:28},{wch:28}];XLSX.utils.book_append_sheet(workbook,teacherSheet,'Teachers');}if(type!=='teachers'){const studentSheet=XLSX.utils.json_to_sheet(students);studentSheet['!cols']=[{wch:24},{wch:24},{wch:24},{wch:12},{wch:10},{wch:18},{wch:24},{wch:24}];XLSX.utils.book_append_sheet(workbook,studentSheet,type==='students'?game.slice(0,31):'Students');}const safeGame=game.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'');const suffix=type==='teachers'?'Teachers':type==='students'?`${safeGame}-Students`:'Archive';const buffer=XLSX.write(workbook,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="CUST-Term-${term.code}-${suffix}.xlsx"`);res.send(buffer);});
app.post('/api/terms/:id/forward',auth,supportOnly,(req,res)=>{const recipient=one("SELECT id,name FROM users WHERE id=? AND status='ACTIVE' AND base_role!='SUPER_ADMIN'",req.body.userId);if(!recipient)return res.status(404).json({message:'Recipient not found'});const term=one('SELECT id,code,name FROM terms WHERE id=?',req.params.id);if(!term)return res.status(404).json({message:'Term not found'});db.prepare(`INSERT INTO term_forwards(term_id,forwarded_by,forwarded_to,message) VALUES(?,?,?,?) ON CONFLICT(term_id,forwarded_to) DO UPDATE SET forwarded_by=excluded.forwarded_by,message=excluded.message,created_at=CURRENT_TIMESTAMP`).run(term.id,req.user.id,recipient.id,req.body.message||'');notify(recipient.id,`Term ${term.code} archive shared`,`${req.user.name} shared the ${term.name} teacher and student archive with you.`,'TERM',req.user.id,`/terms/${term.id}`);res.json({message:`Term archive forwarded to ${recipient.name}`});});

app.get('/api/notifications',auth,(req,res)=>{const received=all("SELECT n.*,u.name sender_name,'RECEIVED' direction,1 recipient_count,CASE WHEN n.is_read=1 THEN 1 ELSE 0 END seen_count FROM notifications n LEFT JOIN users u ON u.id=n.sender_id WHERE n.user_id=? AND n.type!='REMINDER'",req.user.id);const sent=all("SELECT MIN(n.id) id,n.title,n.message,n.type,n.target_url,n.created_at,'SENT' direction,MIN(n.is_read) is_read,COUNT(*) recipient_count,SUM(n.is_read) seen_count,GROUP_CONCAT(u.name,', ') recipient_names FROM notifications n JOIN users u ON u.id=n.user_id WHERE n.sender_id=? AND n.user_id!=n.sender_id AND n.type!='REMINDER' GROUP BY n.title,n.message,n.type,n.target_url,n.created_at",req.user.id);res.json([...received,...sent].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)));});
app.patch('/api/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({message:'Notification read'});});
app.patch('/api/notifications/read-all',auth,(req,res)=>{db.prepare('UPDATE notifications SET is_read=1 WHERE user_id=?').run(req.user.id);res.json({message:'All notifications read'});});
app.delete('/api/notifications/sent/:id',auth,(req,res)=>{const notification=one('SELECT * FROM notifications WHERE id=? AND sender_id=?',req.params.id,req.user.id);if(!notification)return res.status(404).json({message:'Sent notification not found'});db.prepare("DELETE FROM notifications WHERE sender_id=? AND title=? AND message=? AND type=? AND COALESCE(target_url,'')=COALESCE(?,'') AND created_at=?").run(req.user.id,notification.title,notification.message,notification.type,notification.target_url,notification.created_at);res.json({message:'Sent notification deleted'});});
app.delete('/api/notifications/:id',auth,(req,res)=>{const result=db.prepare('DELETE FROM notifications WHERE id=? AND user_id=?').run(req.params.id,req.user.id);if(!result.changes)return res.status(404).json({message:'Notification not found'});res.json({message:'Notification deleted'});});

app.get('/api/reminders',auth,operational,(req,res)=>{const messages=all(`SELECT r.id,r.sender_id senderId,r.recipient_id recipientId,r.message,r.attachment_name attachmentName,r.attachment_url attachmentUrl,r.attachment_type attachmentType,r.is_seen isSeen,r.created_at createdAt,s.name senderName,p.name recipientName FROM reminders r JOIN users s ON s.id=r.sender_id JOIN users p ON p.id=r.recipient_id WHERE r.sender_id=? OR r.recipient_id=? ORDER BY r.created_at DESC`,req.user.id,req.user.id);const conversations=new Map();for(const message of messages){const otherId=message.senderId===req.user.id?message.recipientId:message.senderId;const unreadIncoming=message.recipientId===req.user.id&&!message.isSeen;if(!conversations.has(otherId))conversations.set(otherId,{userId:otherId,name:message.senderId===req.user.id?message.recipientName:message.senderName,lastMessage:unreadIncoming?`${message.senderName} sent you a message`:message.message||message.attachmentType||'Attachment',lastAt:message.createdAt,unread:0});if(unreadIncoming)conversations.get(otherId).unread++;}res.json([...conversations.values()]);});
app.get('/api/reminders/recipients',auth,supportOrHod,(req,res)=>res.json(all(`SELECT u.id,u.name,u.email,u.base_role baseRole,GROUP_CONCAT(CASE WHEN a.status='ACTIVE' THEN CASE WHEN a.assignment_role='SUPPORT_COORDINATOR' THEN 'Support Coordinator' WHEN g.name IS NOT NULL THEN g.name||' Game Head' END END) assignments FROM users u LEFT JOIN assignments a ON a.teacher_id=u.id LEFT JOIN games g ON g.id=a.game_id WHERE u.status='ACTIVE' AND u.base_role!='SUPER_ADMIN' AND u.id!=? GROUP BY u.id ORDER BY CASE u.base_role WHEN 'HOD' THEN 0 ELSE 1 END,u.name`,req.user.id)));
app.get('/api/reminders/:userId',auth,operational,(req,res)=>res.json(all(`SELECT r.id,r.sender_id senderId,r.recipient_id recipientId,r.message,r.attachment_name attachmentName,r.attachment_url attachmentUrl,r.attachment_type attachmentType,r.is_seen isSeen,r.created_at createdAt,s.name senderName,p.name recipientName FROM reminders r JOIN users s ON s.id=r.sender_id JOIN users p ON p.id=r.recipient_id WHERE (r.sender_id=? AND r.recipient_id=?) OR (r.sender_id=? AND r.recipient_id=?) ORDER BY r.created_at`,req.user.id,req.params.userId,req.params.userId,req.user.id)));
app.post('/api/reminders',auth,supportOrHod,reminderUpload.single('attachment'),(req,res)=>{const recipient=one("SELECT id,name FROM users WHERE id=? AND status='ACTIVE' AND base_role!='SUPER_ADMIN'",req.body.recipientId);if(!recipient)return res.status(404).json({message:'Recipient not found'});if(!req.body.message?.trim()&&!req.file)return res.status(400).json({message:'Enter a message or attach a media file'});const attachmentUrl=req.file?`/uploads/reminders/${req.file.filename}`:null;const result=db.prepare('INSERT INTO reminders(sender_id,recipient_id,message,attachment_name,attachment_url,attachment_type) VALUES(?,?,?,?,?,?)').run(req.user.id,recipient.id,req.body.message?.trim()||'',req.file?.originalname||null,attachmentUrl,req.file?.mimetype||null);res.status(201).json({id:Number(result.lastInsertRowid),message:`${req.user.name} sent a message to ${recipient.name}`});});
app.patch('/api/reminders/:userId/seen',auth,operational,(req,res)=>{db.prepare('UPDATE reminders SET is_seen=1 WHERE sender_id=? AND recipient_id=?').run(req.params.userId,req.user.id);res.json({message:'Conversation marked seen'});});
app.delete('/api/reminders/message/:id',auth,operational,(req,res)=>{const message=one('SELECT * FROM reminders WHERE id=? AND (sender_id=? OR recipient_id=?)',req.params.id,req.user.id,req.user.id);if(!message)return res.status(404).json({message:'Message not found'});db.prepare('DELETE FROM reminders WHERE id=?').run(message.id);if(message.attachment_url){const uploadsRoot=path.resolve('uploads/reminders');const filePath=path.resolve(`.${message.attachment_url}`);if(filePath.startsWith(uploadsRoot)&&existsSync(filePath))unlinkSync(filePath);}res.json({message:'Message deleted'});});

if(existsSync('dist')){app.use(express.static('dist'));app.get('/*splat',(req,res)=>res.sendFile(path.resolve('dist/index.html')));}
app.use((err,req,res,next)=>{console.error(err);if(err.code?.includes('CONSTRAINT'))return res.status(409).json({message:'This record already exists or is in use'});res.status(500).json({message:err.message||'Unexpected server error'});});
app.listen(process.env.PORT||4000,()=>console.log(`CUST Sports Week API running on http://localhost:${process.env.PORT||4000}`));
