import {useEffect,useState} from 'react';
import {NavLink,useLocation} from 'react-router-dom';
import {Archive, Bell,ChevronDown,ClipboardList,Gamepad2,LayoutDashboard,LogOut,Menu,MessageSquareText,ShieldCheck,Users,X} from 'lucide-react';
import {useAuth} from '../App';import {api} from '../api';
const roleName=(user)=>user.displayRole||({SUPER_ADMIN:'Super Administrator',HOD:'Head of Department',TEACHER:'Faculty Member'}[user.baseRole]||user.baseRole);
export default function Layout({children}){const{user,logout}=useAuth();const[open,setOpen]=useState(false);const[profile,setProfile]=useState(false);const[count,setCount]=useState(0);const[reminderCount,setReminderCount]=useState(0);const loc=useLocation();
 useEffect(()=>{const refresh=()=>{api.get('/notifications').then(x=>setCount(x.filter(n=>n.direction!=='SENT'&&!n.is_read).length)).catch(()=>{});if(user.baseRole!=='SUPER_ADMIN')api.get('/reminders').then(x=>setReminderCount(x.reduce((total,item)=>total+(item.unread||0),0))).catch(()=>{})};refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[loc.pathname,loc.search,user.baseRole]);
 const links=user.baseRole==='SUPER_ADMIN'
  ? [['/',LayoutDashboard,'Overview'],['/users',Users,'People'],['/notifications',Bell,'Notifications']]
  : [['/',LayoutDashboard,'Overview'],...((user.baseRole==='HOD'||user.displayRole==='Support Coordinator')?[['/users',Users,'People']]:[]),['/games',Gamepad2,'Games'],['/sheets',ClipboardList,'Player Sheets'],...(user.displayRole==='Support Coordinator'?[['/terms',Archive,'Term Archive']]:[]),['/reminders',MessageSquareText,'Reminders'],['/notifications',Bell,'Notifications']];
 return <div className="shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><img src="/cust-logo.jpg"/><div><b>CUST</b><span>Sports Week</span></div><button onClick={()=>setOpen(false)}><X/></button></div><nav><small>WORKSPACE</small>{links.map(([to,Icon,label])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={19}/><span>{label}</span>{label==='Reminders'&&reminderCount>0&&<em>{reminderCount}</em>}{label==='Notifications'&&count>0&&<em>{count}</em>}</NavLink>)}</nav><div className="sidebar-foot"><ShieldCheck size={18}/><div><b>Secure workspace</b><span>Role-based access active</span></div></div></aside><main><header className="topbar"><button className="menu-btn" onClick={()=>setOpen(true)}><Menu/></button><div className="top-title"><span>Capital University of Science & Technology</span><b>Sports Week Management</b></div><div className="top-actions"><NavLink to="/notifications" className="bell"><Bell size={20}/>{count>0&&<i>{count}</i>}</NavLink><button className="profile" onClick={()=>setProfile(!profile)}><span>{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><b>{user.name}</b><small>{roleName(user)}</small></div><ChevronDown size={16}/></button>{profile&&<div className="profile-menu"><div><b>{user.name}</b><span>{user.email}</span></div><button onClick={logout}><LogOut size={17}/> Sign out</button></div>}</div></header><div className="page">{children}</div></main>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</div>}
